annotations:
  charts.openshift.io/name: Illumio Core for Kubernetes
apiVersion: v2
appVersion: 5.9.0
dependencies:
- condition: metrics.enabled
  name: influxdb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 5.6.1
description: A Helm chart of Illumio Core for Kubernetes
icon: https://www.illumio.com/sites/default/files/2021-05/illumio_Logo_2019_0_OPT.svg
kubeVersion: '>=1.20.0-0'
name: illumio
type: application
version: 5.9.0
