{{- if or (eq (lower .Values.clusterMode) "migratelegacytoclas") (eq (lower .Values.clusterMode) "clas") }}
apiVersion: v1
kind: Service
metadata:
  name: illumio-storage
  namespace: {{ include "illumio.namespace" . }}
  {{- if .Values.commonLabels }}
  labels: {{- include "illumio.renderDictionary" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{include "illumio.renderDictionary" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  selector:
    app: illumio-storage
{{- end }}