apiVersion: v1
kind: ConfigMap
metadata:
  name: illumio-config
  namespace: {{ include "illumio.namespace" . }}
  {{- if .Values.commonLabels }}
  labels: {{- include "illumio.renderDictionary" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "illumio.renderDictionary" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  verbosity: {{ .Values.verbosity | default "0" | quote }}
  ignore_cert: {{ .Values.ignore_cert | default "false" | quote }}
  {{- if .Values.networkType }}
  networkType: {{ .Values.networkType  | quote }}
  {{- end }}
  {{- if or (eq (lower .Values.clusterMode) "migratelegacytoclas") (eq (lower .Values.clusterMode) "clas") }}
  waitForPolicyEnabled: {{ .Values.waitForPolicy.enabled | default "false" | quote }}
  waitForPolicyIgnoredNamespaces: {{ include "renderIgnoredNamespaces" $ }}
  waitForPolicyTimeout: {{ .Values.waitForPolicy.timeout | quote }}
  degradedModeEnabled: {{ eq .Values.disableDegradedMode false | quote }}
  reportHostNetworkKubernetesWorkloads: {{ .Values.reportHostNetworkKubernetesWorkloads | default false | quote }}
  degradedModePolicyFail: {{ .Values.degradedModePolicyFail | quote }}
  userAllowedAnnotations: {{ .Values.userAllowedAnnotations | toJson | quote }}
  policyLabelSetEnable: {{ .Values.policyLabelSetEnable | quote }}
  {{- end }}
  pceApiTimeout: {{ .Values.kubelink.pceApiTimeout | quote }}
  pceApiMinBackoff: {{ .Values.kubelink.pceApiMinBackoff | quote }}
  pceApiMaxBackoff: {{ .Values.kubelink.pceApiMaxBackoff | quote }}
  pceApiPolicyInterval: {{ .Values.kubelink.pceApiPolicyInterval | quote }}
  lastAppliedPolicyUpdateInterval: {{ .Values.kubelink.lastAppliedPolicyUpdateInterval | quote }}
  etcdRetryAttempts: {{ .Values.kubelink.etcdRetryAttempts | quote }}
  supportReportVolumeSize: {{ .Values.kubelink.supportReportVolumeSize | default "2Gi" | quote }}
  {{- if .Values.httpProxy }}
  httpProxy: {{ .Values.httpProxy | quote }}
  {{- end }}