# Copyright 2023 Illumio, Inc. All Rights Reserved.
#
# Kubelink
 
{{- if or (eq (lower .Values.clusterMode) "migratelegacytoclas") (eq (lower .Values.clusterMode) "clas") }} 
{{- if (.Values.metrics).enabled }}
apiVersion: v1
kind: Service
metadata:
  name: illumio-kubelink-metrics
  namespace: {{ include "illumio.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: illumio-kubelink
{{- end }}
{{- end }}