# Copyright 2025 Illumio, Inc. All Rights Reserved.
#
# Kubelink

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: illumio-secrets-manager
  namespace: {{ include "illumio.namespace" . }}
  {{- if .Values.commonLabels }}
  labels: {{- include "illumio.renderDictionary" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "illumio.renderDictionary" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - "*"
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete