# Copyright 2024 Illumio, Inc. All Rights Reserved.
#
# Containerizes Virtual Enforcement Node

{{- $varHostBasePath := print .Values.cven.hostBasePath "/illumio_ven_data" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: illumio-ven
  namespace: {{ include "illumio.namespace" . }}
  {{- if .Values.commonLabels }}
  labels: {{- include "illumio.renderDictionary" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "illumio.renderDictionary" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      name: illumio-ven
      {{- if .Values.commonLabels }}
      {{- include "illumio.renderDictionary" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
      {{- end }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 0
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: illumio-ven
        {{- if .Values.commonLabels }}
        {{- include "illumio.renderDictionary" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: illumio-ven
      {{- if .Values.priorityClasses.enabled }}
      priorityClassName:  {{ .Values.priorityClasses.cven }}
      {{- end }}
      hostNetwork: true
      hostPID: true
      {{- if or (eq (lower .Values.clusterMode) "migratelegacytoclas") (eq (lower .Values.clusterMode) "clas") }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{ with .Values.cven.tolerations -}}
      tolerations: {{- toYaml . | nindent 8 -}}
      {{- end -}}
      {{- include "renderPullSecrets" ( dict "images" (list .Values.cven) "context" $ ) | nindent 6 }}
      containers:
        - name: illumio-ven
          image: "{{ .Values.cven.registry }}/{{ .Values.cven.repo }}:{{ .Values.cven.imageTag }}"
          imagePullPolicy: {{ .Values.cven.imagePullPolicy | quote }}
          command:
            - "/ven-init"
            - "{{ eq (lower .Values.clusterMode) "unpair" | ternary "unpair" "activate" }}"
          env:
            - name: ILO_SERVER
              valueFrom:
                secretKeyRef:
                  name: illumio-ven-config
                  key: ilo_server
            - name: ILO_CODE
              valueFrom:
                secretKeyRef:
                  name: illumio-ven-config
                  key: ilo_code
            - name: ILO_MAINTENANCE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: illumio-ven-config
                  key: maintenanceToken
            - name: ILO_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ILO_CONTAINER_RUNTIME
              {{- if eq .Values.containerRuntime "k3s_containerd" }}
              value: containerd
              {{- else }}
              value: {{ .Values.containerRuntime | quote }}
              {{- end }}
            {{- if or (eq (lower .Values.clusterMode) "migratelegacytoclas") (eq (lower .Values.clusterMode) "clas") }}
            - name: ILO_CLAS_MODE
              value: "true"
            - name: ILO_CLUSTER_UUID
              valueFrom:
                secretKeyRef:
                  name: illumio-ven-config
                  key: ilo_cluster_uuid
            {{- end }}
            {{- if ge (int .Values.verbosity) 1 }}
            - name: ILO_DEBUG_MODE
              value: "1"
            {{- end }}
            {{- if eq (lower .Values.enforceNodePortTraffic) "never" }}
            - name: ILO_NODEPORT_DISABLE
              value: "true"
            {{- end }}
            - name: ILO_HOST_BASE_PATH
              value: {{ $varHostBasePath }}
            - name: ILO_PROXY_URI
              valueFrom:
                configMapKeyRef:
                  name: illumio-config
                  key: httpProxy
                  optional: true
            - name: USE_TLS
              value: {{ include "isTLSenabled" . | quote }}
            - name: ILO_FW_BACKEND
              value: {{ .Values.cven.firewallBackend | quote }}
          resources: {{- include "illumio.renderDictionary" ( dict "value" .Values.cven.resources "context" $ ) | nindent 12 }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE", "SYS_ADMIN"]
            privileged: true
          volumeMounts:
            - name: unixsocks
              {{- if eq .Values.containerRuntime "docker" }}
              mountPath: /var/run/docker.sock
              {{- else if eq .Values.containerRuntime "crio" }}
              mountPath: /var/run
              # Ensure that new container network namespaces that get bound under /var/run also show up inside our mount
              mountPropagation: HostToContainer
              {{- else }}
              # Socket for containerd and k3s_containerd
              mountPath: /var/run/containerd/containerd.sock
              {{- end }}
            - name: illumio-ven-data
              mountPath: /opt/illumio_ven_data
            - name: modules
              mountPath: /lib/modules
              readOnly: true
            - name: machine-id
              mountPath: /etc/machine-id
              readOnly: true
            {{- if eq (include "isTLSenabled" .) "true" }}
            - name: tls-certs
              mountPath: /certs/ca.crt
              subPath: ca.crt
              readOnly: true
            {{- end }}
            {{- if .Values.cven.aggressiveTamperingDetection }}
            - name: tracefs
              mountPath: /trace
              readOnly: false
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- include "illumio.renderDictionary" ( dict "value" .Values.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: 60
      volumes:
        - name: unixsocks
          hostPath:
            {{- if eq .Values.containerRuntime "docker" }}
            path: /var/run/docker.sock
            type: Socket
            {{- else if eq .Values.containerRuntime "crio" }}
            path: /var/run
            type: Directory
            {{- else if eq .Values.containerRuntime "k3s_containerd" }}
            # K3s has different path for socket
            path: /var/run/k3s/containerd/containerd.sock
            type: Socket
            {{- else }}
            path: /var/run/containerd/containerd.sock
            type: Socket
            {{- end }}
        - name: illumio-ven-data
          hostPath:
            path: {{ $varHostBasePath }}
            type: DirectoryOrCreate
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: machine-id
          hostPath:
            path: /etc/machine-id
            type: File
        {{- if eq (include "isTLSenabled" .) "true" }}
        - name: tls-certs
          secret:
            secretName: grpc-server-tls
        {{- end }}
        {{- if .Values.cven.aggressiveTamperingDetection }}
        - name: tracefs
          hostPath:
            path: /sys/kernel/tracing
            type: Directory
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- include "illumio.renderDictionary" ( dict "value" .Values.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
