# Copyright 2021 Illumio, Inc. All Rights Reserved.
#
# C-VEN

{{- if eq .Values.containerManager "openshift" }}
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: system:image-puller-illumio-ven
  namespace: {{ include "illumio.namespace" . }}
  {{- if .Values.commonLabels }}
  labels: {{- include "illumio.renderDictionary" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "illumio.renderDictionary" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  name: system:image-puller
subjects:
  - kind: ServiceAccount
    name: illumio-ven
    namespace: {{ include "illumio.namespace" . }}
groupNames:
  - system:serviceaccounts:{{ include "illumio.namespace" . }}
userNames:
  - system:serviceaccount:{{ include "illumio.namespace" . }}:illumio-ven
{{ end }}