# Copyright 2021 Illumio, Inc. All Rights Reserved.
#
# Containerizes Virtual Enforcement Node

apiVersion: v1
kind: Secret
metadata:
  name: illumio-ven-config
  namespace: {{ include "illumio.namespace" . }}
  {{- if .Values.commonLabels }}
  labels: {{- include "illumio.renderDictionary" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "illumio.renderDictionary" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  ilo_server: {{ .Values.pce_url | quote }}
  ilo_code : {{ .Values.cluster_code | quote }}
  ilo_cluster_uuid: {{ .Values.cluster_id | quote }}
  maintenanceToken: {{ .Values.cven.maintenanceToken | quote }}

