# Copyright 2021 Illumio, Inc. All Rights Reserved.
#
# Containerizes Virtual Enforcement Node

{{- if not .Values.argoCD }}
apiVersion: batch/v1
kind: Job
metadata:
  name: illumio-ven-unpair-job
  namespace: {{ include "illumio.namespace" . }}
  {{- if .Values.commonLabels }}
  labels: {{- include "illumio.renderDictionary" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if .Values.commonAnnotations }}
    {{- include "illumio.renderDictionary" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: illumio-pull-secret
      {{- include "renderPullSecrets" ( dict "images" (list .Values.cven) "context" $ ) | nindent 6 }}
      containers:
        - name: illumio-ven-unpair-job
          image: "{{ .Values.cven.registry }}/{{ .Values.cven.repo }}:{{ .Values.cven.imageTag }}"
          imagePullPolicy: {{ .Values.cven.imagePullPolicy | quote }}
          command: ['/bin/sh', '-c']
          args: ["sleep {{ .Values.cven.unpairSleep | default 120 }}"]
{{- end }}